#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CapaDominio	
{
	public partial class Club
	{
		private int idClub;
		public virtual int IdClub
		{
			get
			{
				return this.idClub;
			}
			set
			{
				this.idClub = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private string nombreInstitucional;
		public virtual string NombreInstitucional
		{
			get
			{
				return this.nombreInstitucional;
			}
			set
			{
				this.nombreInstitucional = value;
			}
		}
		
		private string personeriaJuridica;
		public virtual string PersoneriaJuridica
		{
			get
			{
				return this.personeriaJuridica;
			}
			set
			{
				this.personeriaJuridica = value;
			}
		}
		
		private string anioAfiliacion;
		public virtual string AnioAfiliacion
		{
			get
			{
				return this.anioAfiliacion;
			}
			set
			{
				this.anioAfiliacion = value;
			}
		}
		
		private string email;
		public virtual string Email
		{
			get
			{
				return this.email;
			}
			set
			{
				this.email = value;
			}
		}
		
		private string idInterno;
		public virtual string IdInterno
		{
			get
			{
				return this.idInterno;
			}
			set
			{
				this.idInterno = value;
			}
		}
		
		private string telefono;
		public virtual string Telefono
		{
			get
			{
				return this.telefono;
			}
			set
			{
				this.telefono = value;
			}
		}
		
	}
}
#pragma warning restore 1591
