#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class CuotaJugador
	{
		private int idCuotaJugador;
		public virtual int IdCuotaJugador
		{
			get
			{
				return this.idCuotaJugador;
			}
			set
			{
				this.idCuotaJugador = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private decimal? monto;
		public virtual decimal? Monto
		{
			get
			{
				return this.monto;
			}
			set
			{
				this.monto = value;
			}
		}
		
		private string detalle;
		public virtual string Detalle
		{
			get
			{
				return this.detalle;
			}
			set
			{
				this.detalle = value;
			}
		}
		
		private string observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this.observaciones;
			}
			set
			{
				this.observaciones = value;
			}
		}
		
		private string fechaVencimientoMes;
		public virtual string FechaVencimientoMes
		{
			get
			{
				return this.fechaVencimientoMes;
			}
			set
			{
				this.fechaVencimientoMes = value;
			}
		}
		
		private int? fechaVencimientoDia;
		public virtual int? FechaVencimientoDia
		{
			get
			{
				return this.fechaVencimientoDia;
			}
			set
			{
				this.fechaVencimientoDia = value;
			}
		}
		
		private int? fechaVencimientoAnio;
		public virtual int? FechaVencimientoAnio
		{
			get
			{
				return this.fechaVencimientoAnio;
			}
			set
			{
				this.fechaVencimientoAnio = value;
			}
		}
		
		private int? anio;
		public virtual int? Anio
		{
			get
			{
				return this.anio;
			}
			set
			{
				this.anio = value;
			}
		}
		
		private DateTime? fechaVencimiento;
		public virtual DateTime? FechaVencimiento
		{
			get
			{
				return this.fechaVencimiento;
			}
			set
			{
				this.fechaVencimiento = value;
			}
		}
		
		private IList<PagoJugador> pagoJugadors = new List<PagoJugador>();
		public virtual IList<PagoJugador> PagoJugadors
		{
			get
			{
				return this.pagoJugadors;
			}
		}
		
	}
}
#pragma warning restore 1591
