#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CapaDominio;

namespace CapaDominio	
{
	public partial class PagoJugador
	{
		private int idPagoJugador;
		public virtual int IdPagoJugador
		{
			get
			{
				return this.idPagoJugador;
			}
			set
			{
				this.idPagoJugador = value;
			}
		}
		
		private string nombre;
		public virtual string Nombre
		{
			get
			{
				return this.nombre;
			}
			set
			{
				this.nombre = value;
			}
		}
		
		private int idCuotaJugador;
		public virtual int IdCuotaJugador
		{
			get
			{
				return this.idCuotaJugador;
			}
			set
			{
				this.idCuotaJugador = value;
			}
		}
		
		private int idJugador;
		public virtual int IdJugador
		{
			get
			{
				return this.idJugador;
			}
			set
			{
				this.idJugador = value;
			}
		}
		
		private decimal? monto;
		public virtual decimal? Monto
		{
			get
			{
				return this.monto;
			}
			set
			{
				this.monto = value;
			}
		}
		
		private string detalle;
		public virtual string Detalle
		{
			get
			{
				return this.detalle;
			}
			set
			{
				this.detalle = value;
			}
		}
		
		private string observaciones;
		public virtual string Observaciones
		{
			get
			{
				return this.observaciones;
			}
			set
			{
				this.observaciones = value;
			}
		}
		
		private string fechaPagoMes;
		public virtual string FechaPagoMes
		{
			get
			{
				return this.fechaPagoMes;
			}
			set
			{
				this.fechaPagoMes = value;
			}
		}
		
		private int? fechaPagoDia;
		public virtual int? FechaPagoDia
		{
			get
			{
				return this.fechaPagoDia;
			}
			set
			{
				this.fechaPagoDia = value;
			}
		}
		
		private int? fechaPagoAnio;
		public virtual int? FechaPagoAnio
		{
			get
			{
				return this.fechaPagoAnio;
			}
			set
			{
				this.fechaPagoAnio = value;
			}
		}
		
		private int? porcentajeDescuento;
		public virtual int? PorcentajeDescuento
		{
			get
			{
				return this.porcentajeDescuento;
			}
			set
			{
				this.porcentajeDescuento = value;
			}
		}
		
		private DateTime? fechaPago;
		public virtual DateTime? FechaPago
		{
			get
			{
				return this.fechaPago;
			}
			set
			{
				this.fechaPago = value;
			}
		}
		
		private bool? descuento;
		public virtual bool? Descuento
		{
			get
			{
				return this.descuento;
			}
			set
			{
				this.descuento = value;
			}
		}
		
		private Jugador jugador;
		public virtual Jugador Jugador
		{
			get
			{
				return this.jugador;
			}
			set
			{
				this.jugador = value;
			}
		}
		
		private CuotaJugador cuotaJugador;
		public virtual CuotaJugador CuotaJugador
		{
			get
			{
				return this.cuotaJugador;
			}
			set
			{
				this.cuotaJugador = value;
			}
		}
		
	}
}
#pragma warning restore 1591
